Surround Windows mountpoints by double quotes
Windows mount points usually contain colons (e.g: `C:`), but the colon
has a special meaning in YAML, which causes the following exception:

```
Uncaught Exception:
YAMLException: bad indentation of a sequence entry at line 8, column 12:
- path: C:
``````

Fixes: https://github.com/resin-io-modules/drivelist/issues/115
Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>