Escape double quotes inside YAML values
Consider the following description:

	description: "SAMSUNG SSD PM810 2.5" 7mm 256GB"

Because of the double quote in `2.5"`, the YAML parser will complain
with:

	YAMLException: can not read a block mapping entry; a multiline key
	may not be an implicit key at line 2, column 1: